import os
import random

# Method that implements the functions to generate the splits on the dataset to train, validate and test the model
def generate_split(dataset_path: str, percentage_train, percentage_test, percentage_validation=0.0, extension=""):
    """
    Will take a dataset stored, according to:
    _ <dataset_path>
     |_ data
      |_ example_1.npz
      |_ example_2.npz
      |_ ...
      |_ example_n.npz
    _ train.txt
    _ val.txt
    _ test.txt

    where the train.txt, val.txt and test.txt are list that will contain the splits
    of the dataset generated by this function

    Args:
        dataset_path (str): The path to the dataset (absolute or relative)
        percentage_train (float, optional): Defaults to 0.6.
        percentage_validation (float, optional): Defaults to 0.2.
        percentage_test (float, optional): Defaults to 0.2.
        extensions (str): To only consider files with a given extension for the dataset Defaults to ''
    """

    # Check that we can accept the specified percentages for the splits
    assert 0.0 <= percentage_train      <= 1.0
    assert 0.0 <= percentage_test       <= 1.0
    assert 0.0 <= percentage_validation <= 1.0
    assert percentage_train + percentage_validation + percentage_test <= 1.0

    # Get the path where the actual data is stored inside the dataset path
    data_path = os.path.join(dataset_path, "data")

    # List of files that compose the entire dataset
    data_list = os.listdir(data_path)

    # Remove from the datalist any file with a different extension than the specified one
    if extension != "":
        data_list[:] = [file for file in data_list if extension in file]

    # Get the num of files that compose the dataset
    num_files = len(data_list)

    if num_files == 0:
        raise Exception("Dataset " + data_path + " is empty!")

    # Shuffle the list of files
    random.shuffle(data_list)

    # Generate the steps to split the list:
    # train = data_list[0:step_1], val = data_list[step_1:step_2], test = data_list[step_2:step_3]
    step_1 = int(percentage_train * num_files)
    step_2 = step_1 + int(percentage_validation * num_files)
    step_3 = step_2 + int(percentage_test * num_files)

    train = data_list[0:step_1]
    val   = data_list[step_1:step_2]
    test  = data_list[step_2:step_3]

    print("Dataset: " + dataset_path)
    print("Total dataset size: %.0f" % num_files)
    print("Training: %.0f" % len(train))
    print("Validation: %.0f" % len(val))
    print("Test: %.0f" % len(test))

    # Write the names of the files to the corresponding split files
    with open(os.path.join(dataset_path, "train.txt"), 'w') as f:
        for item in train:
            f.write("%s\n" % item)

    with open(os.path.join(dataset_path, "val.txt"), 'w') as f:
        for item in val:
            f.write("%s\n" % item)

    with open(os.path.join(dataset_path, "test.txt"), 'w') as f:
        for item in test:
            f.write("%s\n" % item)

